### ISSUE TITLE
Question about computation of \bar{z}

### ISSUE THREAD

**Issue by vadimkantorov** [akashbapat/domain_transform_solver#1]
Is computation of `\bar{z}` independent of kernel size or radius `r`? If yes, how does the DTS sidestep the loop over `j` in the definition of `\bar{z}`?

Intuitively, does it work with some sort of integral image technique? I must be missing something obvious...

Currently it seems that the computation is proportional to the kernel size as well: https://github.com/akashbapat/domain_transform_solver/blob/master/src/domain_transform_filter.cuh#L41, this code seems to be executed for every pixel (with a loop with number of iterations dependent on kernel size https://github.com/akashbapat/domain_transform_solver/blob/master/src/domain_transform_filter.cuh#L15 )?

Thanks!

**Comment by akashbapat** [comment]
Hi , 
Sorry for the late response, I was busy with work. The  sigma for which the loop runs for is the size of the box filter used in eqn 16 in the paper http://www.inf.ufrgs.br/~eslgastal/DomainTransform/Gastal_Oliveira_SIGGRAPH2011_Domain_Transform.pdf.
The current implementation uses the loop to find out the position of upper and lower bound in the integral image (integrated_var) and then divides by the number of elements to get the mean value. The current implementation does use a sigma_x while setting sigma_z value thats why you might see some weak dependence there. But it doesn't use sigma_color. Its possible to remove the dependence entirely, but its some work. Feel free to ask more questions.

**Comment by akashbapat** [comment]
closing for now.
