### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by oconnor127** [akashbapat/domain_transform_solver#2]
Hey, 

I know It's not a github question, but I will ask it here because there are maybe some people who also want this to know. Is the runtime mentioned in your paper on a GPU or CPU (Multithreaded or Single-Core)? If it is on a CPU, could you maybe give an approximate value of or GPU/Cuda implementation from this repo?

Best

**Comment by akashbapat** [comment]
all time for DTS are for gpu iirc
